import type { MenuCategory } from '@/lib/types';
import { buildCloudinaryImageUrl } from '@/lib/cloudinary';

interface SeedMenuItem {
  slug: string;
  name: string;
  description: string;
  price: number;
  category: MenuCategory;
  prepTime: string;
  calories?: number;
  imagePublicId: string;
  featured?: boolean;
}

export const seedMenuItems: SeedMenuItem[] = [
  {
    slug: 'smoky-burger',
    name: 'Smoky Burger',
    description: 'Beef patty, caramelized onions, cheddar, and pepper mayo.',
    price: 780,
    category: 'signature',
    prepTime: '15 min',
    calories: 820,
    imagePublicId: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    slug: 'peri-peri-wrap',
    name: 'Peri Peri Wrap',
    description: 'Flame-grilled chicken, slaw, and house peri sauce.',
    price: 690,
    category: 'grill',
    prepTime: '12 min',
    calories: 610,
    imagePublicId: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    slug: 'steak-rice-bowl',
    name: 'Steak Rice Bowl',
    description: 'Garlic rice, grilled steak strips, pickled veg, sesame glaze.',
    price: 920,
    category: 'bowls',
    prepTime: '18 min',
    calories: 760,
    imagePublicId: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    slug: 'loaded-fries',
    name: 'Loaded Fries',
    description: 'Crispy fries topped with beef chili and cheese sauce.',
    price: 460,
    category: 'sides',
    prepTime: '10 min',
    calories: 540,
    imagePublicId: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'mango-cheesecake',
    name: 'Mango Cheesecake',
    description: 'Creamy baked cheesecake finished with mango coulis.',
    price: 420,
    category: 'dessert',
    prepTime: '5 min',
    calories: 430,
    imagePublicId: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'hibiscus-fizz',
    name: 'Hibiscus Fizz',
    description: 'Sparkling hibiscus cooler with lime and mint.',
    price: 280,
    category: 'drinks',
    prepTime: '3 min',
    calories: 120,
    imagePublicId: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'safari-bbq-ribs',
    name: 'Safari BBQ Ribs',
    description: 'Sticky pork ribs brushed with tamarind BBQ glaze and kachumbari.',
    price: 1180,
    category: 'signature',
    prepTime: '22 min',
    calories: 980,
    imagePublicId: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    slug: 'charred-chicken-skewers',
    name: 'Charred Chicken Skewers',
    description: 'Spiced chicken skewers, lemon yoghurt, and flame-roasted peppers.',
    price: 740,
    category: 'grill',
    prepTime: '14 min',
    calories: 520,
    imagePublicId: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'coconut-curry-bowl',
    name: 'Coconut Curry Bowl',
    description: 'Coconut curry, basmati rice, chickpeas, greens, and toasted cashews.',
    price: 840,
    category: 'bowls',
    prepTime: '16 min',
    calories: 690,
    imagePublicId: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'plantain-bites',
    name: 'Plantain Bites',
    description: 'Golden plantain, chilli salt, and smoky tomato dip.',
    price: 380,
    category: 'sides',
    prepTime: '8 min',
    calories: 360,
    imagePublicId: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'chocolate-fondant',
    name: 'Chocolate Fondant',
    description: 'Warm chocolate cake with a molten centre and vanilla cream.',
    price: 480,
    category: 'dessert',
    prepTime: '9 min',
    calories: 510,
    imagePublicId: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'passion-ginger-cooler',
    name: 'Passion Ginger Cooler',
    description: 'Passion fruit, ginger syrup, soda, and fresh citrus.',
    price: 320,
    category: 'drinks',
    prepTime: '3 min',
    calories: 140,
    imagePublicId: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'full-kuku-choma',
    name: 'Full Kuku Choma',
    description: 'Whole roasted chicken with smoky char and house seasoning.',
    price: 1800,
    category: 'grill',
    prepTime: '35 min',
    calories: 1800,
    imagePublicId: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    slug: 'full-kuku-fry',
    name: 'Full Kuku Fry',
    description: 'Whole chicken fried with onions, tomatoes, and warm spices.',
    price: 1800,
    category: 'signature',
    prepTime: '30 min',
    calories: 1950,
    imagePublicId: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'mutton-fry-1kg',
    name: '1kg Mutton Fry',
    description: 'Tender mutton fried with savoury aromatics and herbs.',
    price: 1200,
    category: 'signature',
    prepTime: '28 min',
    calories: 1600,
    imagePublicId: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'mutton-choma-1kg',
    name: '1kg Mutton Choma',
    description: 'Char-grilled mutton served hot from the fire.',
    price: 1200,
    category: 'grill',
    prepTime: '32 min',
    calories: 1450,
    imagePublicId: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'beef-fry-1kg',
    name: '1kg Beef Fry',
    description: 'Beef strips fried with onions, tomatoes, and chef spices.',
    price: 1200,
    category: 'signature',
    prepTime: '26 min',
    calories: 1550,
    imagePublicId: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'beef-choma-1kg',
    name: '1kg Beef Choma',
    description: 'Grilled beef with a deep char and simple seasoning.',
    price: 1200,
    category: 'grill',
    prepTime: '30 min',
    calories: 1380,
    imagePublicId: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'fish-fry',
    name: 'Fish Fry',
    description: 'Crisp fried fish finished with lemon and tomato relish.',
    price: 650,
    category: 'signature',
    prepTime: '20 min',
    calories: 620,
    imagePublicId: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'managu-greens',
    name: 'Managu Greens',
    description: 'Traditional greens sauteed lightly with onions and tomatoes.',
    price: 150,
    category: 'sides',
    prepTime: '10 min',
    calories: 110,
    imagePublicId: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'pork-ribs',
    name: 'Pork Ribs',
    description: 'Juicy pork ribs grilled and glazed for a rich finish.',
    price: 500,
    category: 'grill',
    prepTime: '24 min',
    calories: 820,
    imagePublicId: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'broiler-choma',
    name: 'Broiler Choma',
    description: 'Flame-roasted broiler chicken with crispy skin.',
    price: 1400,
    category: 'grill',
    prepTime: '30 min',
    calories: 1500,
    imagePublicId: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'coffee',
    name: 'Coffee',
    description: 'Fresh brewed hot coffee.',
    price: 150,
    category: 'drinks',
    prepTime: '4 min',
    calories: 5,
    imagePublicId: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'tea',
    name: 'Tea',
    description: 'Classic Kenyan-style hot tea.',
    price: 150,
    category: 'drinks',
    prepTime: '5 min',
    calories: 90,
    imagePublicId: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'milo',
    name: 'Milo',
    description: 'Hot malt chocolate drink.',
    price: 150,
    category: 'drinks',
    prepTime: '5 min',
    calories: 170,
    imagePublicId: 'https://images.unsplash.com/photo-1517578239113-b03992dcdd25?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'dawa-herbal-tea',
    name: 'Dawa Herbal Tea',
    description: 'Herbal tea with lemon, ginger, and honey notes.',
    price: 200,
    category: 'drinks',
    prepTime: '6 min',
    calories: 80,
    imagePublicId: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'fresh-juice',
    name: 'Fresh Juice',
    description: 'Seasonal fresh fruit juice served chilled.',
    price: 200,
    category: 'drinks',
    prepTime: '4 min',
    calories: 130,
    imagePublicId: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'soda',
    name: 'Soda',
    description: 'Chilled bottled soda.',
    price: 100,
    category: 'drinks',
    prepTime: '2 min',
    calories: 140,
    imagePublicId: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'delmonte-juice',
    name: 'Delmonte Juice',
    description: 'Premium packaged fruit juice.',
    price: 400,
    category: 'drinks',
    prepTime: '2 min',
    calories: 160,
    imagePublicId: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'cabbage',
    name: 'Cabbage',
    description: 'Lightly cooked cabbage with mild seasoning.',
    price: 100,
    category: 'sides',
    prepTime: '8 min',
    calories: 70,
    imagePublicId: 'https://images.unsplash.com/photo-1594282486552-05a21110f1c4?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'kachumbari',
    name: 'Kachumbari',
    description: 'Fresh tomato and onion salad with coriander and lemon.',
    price: 100,
    category: 'sides',
    prepTime: '5 min',
    calories: 60,
    imagePublicId: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'sukuma-wiki',
    name: 'Sukuma Wiki',
    description: 'Collard greens sauteed with onions.',
    price: 100,
    category: 'sides',
    prepTime: '8 min',
    calories: 90,
    imagePublicId: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'sausage',
    name: 'Sausage',
    description: 'Pan-fried breakfast sausage.',
    price: 80,
    category: 'sides',
    prepTime: '6 min',
    calories: 220,
    imagePublicId: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'mandazi',
    name: 'Mandazi',
    description: 'Soft fried dough snack with a golden crust.',
    price: 50,
    category: 'dessert',
    prepTime: '5 min',
    calories: 210,
    imagePublicId: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'samosa',
    name: 'Samosa',
    description: 'Crisp pastry filled with spiced savoury filling.',
    price: 70,
    category: 'sides',
    prepTime: '6 min',
    calories: 180,
    imagePublicId: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'kebab',
    name: 'Kebab',
    description: 'Seasoned grilled kebab with a savoury bite.',
    price: 100,
    category: 'grill',
    prepTime: '8 min',
    calories: 260,
    imagePublicId: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'chapati',
    name: 'Chapati',
    description: 'Soft layered flatbread.',
    price: 50,
    category: 'sides',
    prepTime: '5 min',
    calories: 170,
    imagePublicId: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'brown-chapati',
    name: 'Brown Chapati',
    description: 'Whole wheat chapati with a hearty finish.',
    price: 100,
    category: 'sides',
    prepTime: '5 min',
    calories: 160,
    imagePublicId: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'ugali-brown',
    name: 'Ugali Brown',
    description: 'Brown ugali made from whole grain flour.',
    price: 100,
    category: 'sides',
    prepTime: '8 min',
    calories: 210,
    imagePublicId: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'ugali-white',
    name: 'Ugali White',
    description: 'Classic white maize ugali.',
    price: 50,
    category: 'sides',
    prepTime: '8 min',
    calories: 190,
    imagePublicId: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'chips-plain',
    name: 'Chips Plain',
    description: 'Crispy plain fries served hot.',
    price: 200,
    category: 'sides',
    prepTime: '10 min',
    calories: 480,
    imagePublicId: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'chips-masala',
    name: 'Chips Masala',
    description: 'Fries tossed in a rich masala sauce.',
    price: 250,
    category: 'sides',
    prepTime: '12 min',
    calories: 560,
    imagePublicId: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'rice',
    name: 'Rice',
    description: 'Steamed white rice.',
    price: 150,
    category: 'bowls',
    prepTime: '8 min',
    calories: 240,
    imagePublicId: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'pilau',
    name: 'Pilau',
    description: 'Spiced rice cooked with warm coastal aromatics.',
    price: 200,
    category: 'bowls',
    prepTime: '12 min',
    calories: 410,
    imagePublicId: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'roast-potatoes',
    name: 'Roast Potatoes',
    description: 'Golden roast potatoes with crisp edges.',
    price: 200,
    category: 'sides',
    prepTime: '12 min',
    calories: 320,
    imagePublicId: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1200&q=80',
  },
];

export const fallbackMenuItems = seedMenuItems.map((item, index) => ({
  id: `seed-${index + 1}`,
  ...item,
  imageUrl: buildCloudinaryImageUrl(item.imagePublicId),
}));
